# NUMPY -Numerical Python
# SCIPY - Scientific Python

## Problems like
## 1. Arrays
## 2. matrices
## 3. Integration
## 4. Differential Equations
## 5. Statistics

### *basically Python is not having any fundamental buit-ins to solve these type of problems so we use Numpy library 

### *Scipy is built on numpy framework to solve advanced mathematical caluclations

## ** ARRAYS: Genererally Array means Arraning things in a particular way. In programming Array means collection of elements of same Data-type. Array is also a Data Structure.

### in Python we can store store data in many formats like lists,dicts,Arrays.
### * Arrays are same as list where we can do indexing,slicing, but the only difference is here store the values of same data-type where as in list we can store values of any data-type.

### * In Numpy-Array we can do some  mathematical caluclations where as in list we cannot and more over to create a list we dont need any libraries but to create a numpy array we need numpy library. 

### * numpy arrays occupy very less-space and also work very fast when compared to lists.

## * In Numpy we can have Arrays of any dimension (1D,2D,3D,.......)

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b=np.array([1,2,3,4], dtype="complex")

In [6]:
b

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [7]:
c=np.array([1,2,3,4],dtype="float")

In [8]:
c

array([1., 2., 3., 4.])

In [9]:
cd=a+b+c

In [10]:
cd

array([ 3.+0.j,  6.+0.j,  9.+0.j, 12.+0.j])

In [11]:
b2=int(b)

TypeError: only size-1 arrays can be converted to Python scalars

## * we can convert the elements in to any dtype while creating an array but after creating we cant convert into another dtype

In [17]:
tup=np.array((1,2,3,4),"complex")

In [18]:
tup

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

### * we can create an array by using tuple also

## * Numpy Array consists of many function
## 1.range function
## 2. linspace function
## 3.Zeros Function
## 4.ones Function
## 5.Eye Function
## 6.Random Function

# RANGE FUNCTION

### * It is an Array that creates evenly spaced numeric  values

In [19]:
r1=np.arange(1,10,1)

In [20]:
r1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
r2=np.arange(2,50,5, dtype="complex")

In [24]:
r2

array([ 2.+0.j,  7.+0.j, 12.+0.j, 17.+0.j, 22.+0.j, 27.+0.j, 32.+0.j,
       37.+0.j, 42.+0.j, 47.+0.j])

In [25]:
r3=np.arange(15)

In [26]:
r3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
r4=np.arange(1,10,1,"complex")

In [28]:
r4

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j,
       9.+0.j])

In [29]:
r5=np.arange(1.0,10.0,1.0)

In [30]:
r5

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

# ZEROS FUNCTION

In [37]:
z1=np.zeros((5,5))

In [38]:
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
z2=np.zeros((3,3),"complex",order={"F"})

C:\Users\Hp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  """Entry point for launching an IPython kernel.


In [52]:
z2

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [55]:
z3=np.zeros(5)

In [56]:
z3

array([0., 0., 0., 0., 0.])

# ONES FUNCTION

In [57]:
z1=np.ones(5)

In [58]:
z1

array([1., 1., 1., 1., 1.])

In [59]:
z2=np.ones([5,5],dtype="complex")

In [60]:
z2

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

# LINSPACE FUNCTION

### *Here we are getting values of even space with in a given range and how many elements we required
### * here stop value is also included

In [61]:
l1=np.linspace(1,10,100)

In [62]:
l1

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

### "retstep" will give us the step difference between 2 numbers
### we can also give endpoint="False" it will consider last number
### num default value is 50 so we can get 50 values without mentioning.

In [70]:
l2=np.linspace(1,10,dtype="complex",retstep="True")

In [71]:
l2

(array([ 1.        +0.j,  1.18367347+0.j,  1.36734694+0.j,  1.55102041+0.j,
         1.73469388+0.j,  1.91836735+0.j,  2.10204082+0.j,  2.28571429+0.j,
         2.46938776+0.j,  2.65306122+0.j,  2.83673469+0.j,  3.02040816+0.j,
         3.20408163+0.j,  3.3877551 +0.j,  3.57142857+0.j,  3.75510204+0.j,
         3.93877551+0.j,  4.12244898+0.j,  4.30612245+0.j,  4.48979592+0.j,
         4.67346939+0.j,  4.85714286+0.j,  5.04081633+0.j,  5.2244898 +0.j,
         5.40816327+0.j,  5.59183673+0.j,  5.7755102 +0.j,  5.95918367+0.j,
         6.14285714+0.j,  6.32653061+0.j,  6.51020408+0.j,  6.69387755+0.j,
         6.87755102+0.j,  7.06122449+0.j,  7.24489796+0.j,  7.42857143+0.j,
         7.6122449 +0.j,  7.79591837+0.j,  7.97959184+0.j,  8.16326531+0.j,
         8.34693878+0.j,  8.53061224+0.j,  8.71428571+0.j,  8.89795918+0.j,
         9.08163265+0.j,  9.26530612+0.j,  9.44897959+0.j,  9.63265306+0.j,
         9.81632653+0.j, 10.        +0.j]),
 0.1836734693877551)

# EYE FUNCTION

##  It will return all values to zero except the kth diagonal and we can select that kth  and in that diagonal all values will be 1

In [72]:
e1=np.eye(5,5,2)

In [73]:
e1

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
e2=np.eye(6,6,0,"int")

In [77]:
e2

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

## for all the functions we can mention "ORDER" that means in which way to store in our memory, we are having 2 memories C and F 
## C means row memory
## F means column memory

In [82]:
e3=np.eye(5,5,-1,"complex")

### we can give k value also as -1

In [83]:
e3

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]])

# RANDOM FUNCTION

## "rand" will give the uniformly distributed matrix with  values ranging from 0 and 1

In [84]:
r1=np.random.rand(3,5)

In [85]:
r1

array([[0.80075061, 0.44115863, 0.65973008, 0.55529387, 0.63770496],
       [0.45843945, 0.02893885, 0.69740905, 0.06069099, 0.92521406],
       [0.11095024, 0.09453027, 0.6532718 , 0.45621618, 0.10812215]])

## "randn" it will give the normally distributed matrix with values ranges between -1 and 1

In [86]:
np.random.randn(3,5)

array([[-0.3943094 , -0.70382708,  0.28260935, -0.76045226,  0.31805033],
       [ 1.08710219,  0.28550189, -1.24663563,  0.67903634, -0.65668816],
       [ 0.16825694,  0.48224996,  1.38956032,  0.72511437, -0.43713522]])

## "ranf" will give us uniformly distributed floating values and matrix of given shape (uniform distribution means values will be between 0 and 1

In [105]:
np.random.ranf((5,))

array([0.00465623, 0.86495737, 0.48051545, 0.4673714 , 0.94912001])

In [110]:
a=np.random.ranf((3,3))

In [111]:
a

array([[0.01689178, 0.46937024, 0.18720897],
       [0.92863107, 0.13092081, 0.95696087],
       [0.651939  , 0.12199532, 0.61433444]])

## "randint" will give the uniformly distributed integer values  and matrix between given range and how many number of integers we want and size of the matrix required.

In [107]:
np.random.randint(3,5,10)

array([3, 4, 4, 3, 3, 4, 3, 4, 4, 3])

In [108]:
np.random.randint(low=6,size=(2,3))

array([[5, 5, 2],
       [5, 0, 0]])

# DIMENSION of the array

In [114]:
a=np.array([1,2,3])

In [115]:
a.ndim

1

In [120]:
b=np.array([[1,2,3],[4,5,6]])

In [121]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
b.ndim

2

In [125]:
b.shape

(2, 3)

In [133]:
c=np.zeros((2,3,5))

In [134]:
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

# dimension,shape,size,data-type,item-size

In [135]:
c.ndim

3

In [136]:
c.shape

(2, 3, 5)

In [137]:
c.size

30

In [139]:
c.dtype

dtype('float64')

In [141]:
c.itemsize       # each element will take 4 bytes of data

8

# DATA TYPES

## 1.int
## 2.float
## 3.object
## 4.bool
## 5.complex


### int 64  it is a 8 byte integer (1 byte=8 bits) consists of both -ve and +ve values.
### uint64 it is a un-signed integer, it does not have any -ve values.

In [142]:
a=np.zeros(5)

In [148]:
a.itemsize

1

In [144]:
a.dtype

dtype('float64')

In [154]:
a=np.zeros(5,dtype="complex")

In [162]:
a

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [163]:
a.astype("str")

array(['0j', '0j', '0j', '0j', '0j'], dtype='<U64')

In [164]:
a.astype("int")

C:\Users\Hp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 0, 0])

In [165]:
a.astype("bool")

array([False, False, False, False, False])

In [153]:
a.itemsize

1

In [169]:
b=np.random.randint(3,9,size=(3,3))

In [170]:
b

array([[8, 5, 8],
       [4, 3, 3],
       [6, 4, 5]])

In [171]:
b.astype("float")

array([[8., 5., 8.],
       [4., 3., 3.],
       [6., 4., 5.]])

In [172]:
b.astype("complex")

array([[8.+0.j, 5.+0.j, 8.+0.j],
       [4.+0.j, 3.+0.j, 3.+0.j],
       [6.+0.j, 4.+0.j, 5.+0.j]])

In [173]:
b.astype("bool")

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [175]:
np.random.rand(3,5)

array([[0.30770788, 0.90457161, 0.11699426, 0.81771639, 0.02328138],
       [0.96679079, 0.51304589, 0.17047305, 0.36143672, 0.17708212],
       [0.55089251, 0.68849223, 0.65270263, 0.11837743, 0.88069557]])

In [176]:
np.random.randn(3,5)

array([[ 0.86301461, -0.34149634,  0.84434208,  0.2850942 ,  1.40480869],
       [ 1.07227367, -0.16965067, -0.39581436,  0.39541961, -0.59253   ],
       [-1.88291052, -0.72058168,  0.19444946,  1.26903199,  0.05428235]])

In [180]:
np.random.ranf(size=(5,5,5))

array([[[0.05812475, 0.90232299, 0.57659731, 0.37891976, 0.2492294 ],
        [0.28330888, 0.17460252, 0.28034873, 0.27064861, 0.60891613],
        [0.01640044, 0.23788841, 0.49655142, 0.31501719, 0.06192355],
        [0.29240456, 0.47360614, 0.11083126, 0.87761767, 0.22265394],
        [0.9505678 , 0.65660342, 0.18842202, 0.16963791, 0.53432904]],

       [[0.00563647, 0.4513599 , 0.49207854, 0.14854728, 0.08020192],
        [0.08647189, 0.04953672, 0.18959741, 0.27378917, 0.42937332],
        [0.34788171, 0.74731171, 0.97146728, 0.78125414, 0.92451   ],
        [0.67504347, 0.00284129, 0.73250322, 0.27917425, 0.31676393],
        [0.50016816, 0.79870757, 0.84126468, 0.33663243, 0.36574096]],

       [[0.02461992, 0.84391854, 0.31382624, 0.73364616, 0.34030676],
        [0.42538323, 0.39410711, 0.90728946, 0.39726613, 0.75870021],
        [0.65172776, 0.77179056, 0.00859338, 0.468581  , 0.54131141],
        [0.23513697, 0.39996603, 0.46901075, 0.08556101, 0.54747878],
        [0.38933

In [181]:
np.random.randint(1,10,size=(5,5))

array([[6, 8, 4, 4, 2],
       [5, 9, 5, 7, 7],
       [6, 2, 2, 4, 1],
       [7, 9, 1, 2, 1],
       [2, 1, 2, 1, 8]])

# Conversions

In [156]:
d=64.0

In [157]:
int(d)

64

In [158]:
float(d)

64.0

In [159]:
complex(d)

(64+0j)

In [160]:
bool(d)

True

In [161]:
str(d)

'64.0'

# indexing and slicing

## *indexing for 2 dimension will be in the form of a[i][j]
## *negative indexing also can be given

In [182]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [183]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [185]:
a[1][3]

8

In [186]:
a[0][2]

3

In [187]:
a[-1][-2]

7

In [188]:
a[0]

array([1, 2, 3, 4])

## for 3D indexing a[i][j][k]

## i= in 3D what is the matrix number

## j= row
## k=column

In [190]:
d=np.random.randint(2,10,size=(3,3,3))

In [191]:
d

array([[[6, 3, 6],
        [9, 7, 7],
        [8, 5, 4]],

       [[3, 3, 4],
        [8, 7, 8],
        [4, 9, 4]],

       [[6, 8, 9],
        [4, 4, 6],
        [9, 7, 2]]])

In [192]:
d[0][1][1]

7

# advanced indexing

In [9]:
import numpy as np
a=np.arange(1,10,1)

In [10]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
index=np.array([1,4,5])

In [13]:
a[index]

array([2, 5, 6])

# 2nd method

In [14]:
a[[1,4,5]]

array([2, 5, 6])

## Repetition of indexing

In [24]:
a[[1,4,1,4,1,4]]

array([2, 5, 2, 5, 2, 5])

In [15]:
b=np.random.randint(1,20,size=(5,5))

### Multi dimensional advanced indexing

In [16]:
b

array([[14, 18,  8,  9, 10],
       [12, 18,  1, 19,  9],
       [12,  5,  1, 14, 17],
       [15, 11,  8,  5,  8],
       [17, 18,  4, 16,  9]])

In [17]:
b[[1],[3]]

array([19])

In [20]:
b[[0,4],[0,4]]

array([14,  9])

In [22]:
b[[1],[1,3]]

array([18, 19])

# Boolean Indexing (giving condition)

In [26]:
c=np.array([[1,2,3,4],[5,6,7,8]])

In [27]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
c[c<4]

array([1, 2, 3])

In [29]:
c[c>2]

array([3, 4, 5, 6, 7, 8])

In [30]:
c[c>=1]*10

array([10, 20, 30, 40, 50, 60, 70, 80])

In [33]:
d=c[[0,1],[1,1]]*10

In [34]:
d

array([20, 60])

# Slicing

In [35]:
c[0:,1:3]

array([[2, 3],
       [6, 7]])

# Arithmetic Operations
## 1.scalar(constant element)
## 2.in between arrays

In [38]:
s=np.arange(1,10,1)

In [39]:
s

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
s+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
s*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
s/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [43]:
s-10

array([-9, -8, -7, -6, -5, -4, -3, -2, -1])

In [54]:
s**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [47]:
p=np.arange(11,20,1)

In [48]:
p

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
s+p

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [50]:
s-p

array([-10, -10, -10, -10, -10, -10, -10, -10, -10])

In [51]:
s*p

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [52]:
s/p

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

In [57]:
a=np.random.randint(1,10,size=(4,5))

In [58]:
a

array([[3, 8, 5, 9, 3],
       [1, 3, 9, 5, 3],
       [1, 7, 9, 9, 1],
       [6, 9, 4, 1, 6]])

In [59]:
b=np.random.rand(4,5)

In [60]:
b

array([[0.85110747, 0.85405501, 0.91097013, 0.17483745, 0.58492273],
       [0.06340009, 0.35642822, 0.65203359, 0.58389732, 0.25634102],
       [0.1566194 , 0.92537723, 0.5433381 , 0.75703687, 0.23742296],
       [0.69679108, 0.28754482, 0.54149271, 0.26733111, 0.49990254]])

In [61]:
c=np.random.randn(4,5)

In [62]:
c

array([[ 1.66770872,  1.06194132, -0.21706179, -1.94311127,  1.14782735],
       [-0.50045902,  0.58573541,  0.54456585,  0.85246313, -0.16339039],
       [ 0.85178583,  0.42947105,  1.51506091,  1.6112059 , -0.99643837],
       [-1.18774485,  0.01797191, -0.91516095, -0.52478372,  1.60398158]])

In [65]:
d=np.random.ranf(size=(4,5))

In [66]:
d

array([[0.95140562, 0.47823393, 0.5246374 , 0.38339906, 0.60012528],
       [0.15948767, 0.51910409, 0.46494236, 0.70724779, 0.84589917],
       [0.16541993, 0.90606173, 0.00716236, 0.15844327, 0.01189332],
       [0.83717162, 0.17322668, 0.01834425, 0.86156886, 0.4374113 ]])

In [67]:
a+b

array([[3.85110747, 8.85405501, 5.91097013, 9.17483745, 3.58492273],
       [1.06340009, 3.35642822, 9.65203359, 5.58389732, 3.25634102],
       [1.1566194 , 7.92537723, 9.5433381 , 9.75703687, 1.23742296],
       [6.69679108, 9.28754482, 4.54149271, 1.26733111, 6.49990254]])

In [68]:
a*d

array([[2.85421686, 3.82587144, 2.62318701, 3.45059155, 1.80037584],
       [0.15948767, 1.55731226, 4.18448121, 3.53623893, 2.53769752],
       [0.16541993, 6.34243212, 0.0644612 , 1.4259894 , 0.01189332],
       [5.02302969, 1.55904013, 0.07337701, 0.86156886, 2.62446778]])

In [69]:
np.add(a,b)

array([[3.85110747, 8.85405501, 5.91097013, 9.17483745, 3.58492273],
       [1.06340009, 3.35642822, 9.65203359, 5.58389732, 3.25634102],
       [1.1566194 , 7.92537723, 9.5433381 , 9.75703687, 1.23742296],
       [6.69679108, 9.28754482, 4.54149271, 1.26733111, 6.49990254]])

In [70]:
np.subtract(a,b)

array([[2.14889253, 7.14594499, 4.08902987, 8.82516255, 2.41507727],
       [0.93659991, 2.64357178, 8.34796641, 4.41610268, 2.74365898],
       [0.8433806 , 6.07462277, 8.4566619 , 8.24296313, 0.76257704],
       [5.30320892, 8.71245518, 3.45850729, 0.73266889, 5.50009746]])

In [71]:
np.multiply(a,b)

array([[2.5533224 , 6.8324401 , 4.55485064, 1.57353702, 1.75476819],
       [0.06340009, 1.06928465, 5.86830233, 2.91948661, 0.76902306],
       [0.1566194 , 6.47764061, 4.89004288, 6.8133318 , 0.23742296],
       [4.18074646, 2.58790342, 2.16597086, 0.26733111, 2.99941523]])

# Broadcasting (Performing Arthimetic Operations of different shape)

In [72]:
a=np.arange(1,10,1)

In [73]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
b=np.arange(1,5,1)

In [75]:
b

array([1, 2, 3, 4])

## 1.  we need to check the shape of the array.
## 2. Thenwe need to check the dimension, if dimensions are not equal then add 1 to  lower dimension on left side if it is 1 dimentional,  if not check any one of the array is having shape 1............ if contains1 ok if not we cannot perform operations.
### 3.if contains dimension 1 then coming from right c that both are equal are not, if equal then we can perform operations

In [76]:
c=np.random.randint(1,5,size=(3,2))

In [ ]:
d=np.arange(1,3,1)

### Higher dimension column must be equal to lower dimension column then we can perform Arthimetic operations, output will be in the form of higher dimension only.

In [78]:
c

array([[3, 1],
       [1, 2],
       [2, 2]])

In [80]:
d

array([1, 2])

In [81]:
c+d

array([[4, 3],
       [2, 4],
       [3, 4]])

In [82]:
c*d

array([[3, 2],
       [1, 4],
       [2, 4]])

In [83]:
e=np.random.randint(1,10,size=(3,1))

In [88]:
e.shape

(3, 1)

In [85]:
f=np.arange(1,4)

In [89]:
f.shape

(3,)

## Here e is 3 Dimension and f is lower dimension so add 1 to f on left side ,comparing both are having 1 so stretching will happen and perform operations

In [87]:
e+f

array([[ 4,  5,  6],
       [10, 11, 12],
       [ 2,  3,  4]])

# ARRAY MANIPULATION

### Changing of everything in an array will comes under manipulation.

## Re-shape and Re-size

In [94]:
a=np.random.ranf(size=(4,5))

In [95]:
a

array([[0.08935258, 0.4152992 , 0.91372188, 0.89811809, 0.28513197],
       [0.54693822, 0.85064972, 0.3949214 , 0.70660196, 0.78446256],
       [0.96503296, 0.55124978, 0.22620422, 0.77671129, 0.33384839],
       [0.17699872, 0.29111009, 0.30296262, 0.62482199, 0.239056  ]])

In [96]:
b=np.reshape(a,(5,4))

In [97]:
c=np.reshape(a,(5,4),order="F")

In [98]:

b

array([[0.08935258, 0.4152992 , 0.91372188, 0.89811809],
       [0.28513197, 0.54693822, 0.85064972, 0.3949214 ],
       [0.70660196, 0.78446256, 0.96503296, 0.55124978],
       [0.22620422, 0.77671129, 0.33384839, 0.17699872],
       [0.29111009, 0.30296262, 0.62482199, 0.239056  ]])

In [99]:
c

array([[0.08935258, 0.85064972, 0.22620422, 0.62482199],
       [0.54693822, 0.55124978, 0.30296262, 0.28513197],
       [0.96503296, 0.29111009, 0.89811809, 0.78446256],
       [0.17699872, 0.91372188, 0.70660196, 0.33384839],
       [0.4152992 , 0.3949214 , 0.77671129, 0.239056  ]])

In [100]:
b.shape,b.size

((5, 4), 20)

In [101]:
c.shape,c.size

((5, 4), 20)

In [102]:
b.reshape((5,4))

array([[0.08935258, 0.4152992 , 0.91372188, 0.89811809],
       [0.28513197, 0.54693822, 0.85064972, 0.3949214 ],
       [0.70660196, 0.78446256, 0.96503296, 0.55124978],
       [0.22620422, 0.77671129, 0.33384839, 0.17699872],
       [0.29111009, 0.30296262, 0.62482199, 0.239056  ]])

# Re-size will change the data of the array but in resize we can resize it to any shape, if we take the higher shape elements may be repeated.

In [104]:
f=np.resize(b,(3,3))

In [105]:
f

array([[0.08935258, 0.4152992 , 0.91372188],
       [0.89811809, 0.28513197, 0.54693822],
       [0.85064972, 0.3949214 , 0.70660196]])

In [106]:
g=np.resize(b,(6,5))

In [107]:
g

array([[0.08935258, 0.4152992 , 0.91372188, 0.89811809, 0.28513197],
       [0.54693822, 0.85064972, 0.3949214 , 0.70660196, 0.78446256],
       [0.96503296, 0.55124978, 0.22620422, 0.77671129, 0.33384839],
       [0.17699872, 0.29111009, 0.30296262, 0.62482199, 0.239056  ],
       [0.08935258, 0.4152992 , 0.91372188, 0.89811809, 0.28513197],
       [0.54693822, 0.85064972, 0.3949214 , 0.70660196, 0.78446256]])

# this will directly change the input data also

In [109]:
b.resize((5,4))

In [110]:
b

array([[0.08935258, 0.4152992 , 0.91372188, 0.89811809],
       [0.28513197, 0.54693822, 0.85064972, 0.3949214 ],
       [0.70660196, 0.78446256, 0.96503296, 0.55124978],
       [0.22620422, 0.77671129, 0.33384839, 0.17699872],
       [0.29111009, 0.30296262, 0.62482199, 0.239056  ]])

## * flattening any dimension array into 1D

In [111]:
b.flatten()

array([0.08935258, 0.4152992 , 0.91372188, 0.89811809, 0.28513197,
       0.54693822, 0.85064972, 0.3949214 , 0.70660196, 0.78446256,
       0.96503296, 0.55124978, 0.22620422, 0.77671129, 0.33384839,
       0.17699872, 0.29111009, 0.30296262, 0.62482199, 0.239056  ])

In [112]:
b.flatten("F")

array([0.08935258, 0.28513197, 0.70660196, 0.22620422, 0.29111009,
       0.4152992 , 0.54693822, 0.78446256, 0.77671129, 0.30296262,
       0.91372188, 0.85064972, 0.96503296, 0.33384839, 0.62482199,
       0.89811809, 0.3949214 , 0.55124978, 0.17699872, 0.239056  ])

In [113]:
np.ravel(b)

array([0.08935258, 0.4152992 , 0.91372188, 0.89811809, 0.28513197,
       0.54693822, 0.85064972, 0.3949214 , 0.70660196, 0.78446256,
       0.96503296, 0.55124978, 0.22620422, 0.77671129, 0.33384839,
       0.17699872, 0.29111009, 0.30296262, 0.62482199, 0.239056  ])

### *both flatten and  ravel will flatten the array into 1D but flatten will return theoutput but ravel will store the output and give us when ever required it only gives us the view

# TRASPOSE AND SWAP-AXIS

### Transpose means just transpose of dimension only
### * we can apply transpose on any dimension it will reverse it and if we apply on 1D array it wiil remain same.
### * transpose may also depend on axes we are giving,
### 1.axes=(1,0) - transpose occur
### 2.axes=(0,1) - transpose does not occur
## * axes will play a crucial role in transpose when we go for higher dimension.


In [122]:
a=np.arange(1,13).reshape(3,4)

In [123]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [124]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [126]:
np.transpose(a)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [129]:
np.transpose(a,axes=(1,0))

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [130]:
np.transpose(a,axes=(0,1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
b=np.arange(1,11).reshape(1,5,2)

In [142]:
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

In [135]:
np.transpose(b,axes=(2,1,0))

array([[[ 1, 11, 21, 31],
        [ 3, 13, 23, 33],
        [ 5, 15, 25, 35],
        [ 7, 17, 27, 37],
        [ 9, 19, 29, 39]],

       [[ 2, 12, 22, 32],
        [ 4, 14, 24, 34],
        [ 6, 16, 26, 36],
        [ 8, 18, 28, 38],
        [10, 20, 30, 40]]])

## Swap-axis is used to inter-change only 2 axis

In [144]:
np.swapaxes(b,0,1)

array([[[ 1,  2]],

       [[ 3,  4]],

       [[ 5,  6]],

       [[ 7,  8]],

       [[ 9, 10]]])

In [145]:
np.swapaxes(b,1,0)

array([[[ 1,  2]],

       [[ 3,  4]],

       [[ 5,  6]],

       [[ 7,  8]],

       [[ 9, 10]]])

In [146]:
np.arange(1,25).reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [149]:
g=np.arange(1,33).reshape(2,4,4)

In [151]:
np.swapaxes(g,2,1)

array([[[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]],

       [[17, 21, 25, 29],
        [18, 22, 26, 30],
        [19, 23, 27, 31],
        [20, 24, 28, 32]]])

## Joining of numpy arrays,Concatinating, 
## for concatinating Dimensions must match.

In [152]:
a=np.arange(1,10,1)

In [153]:
b=np.arange(11,20,1)

In [158]:
c=np.concatenate((a,b))

In [159]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [165]:
a=np.arange(1,10,1).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
b=np.arange(11,20,1).reshape(3,3)
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [163]:
c=np.concatenate((a,b))

In [164]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [167]:
c.shape

(6, 3)

# 5 DIMENSIONAL ARRAY

In [180]:
d=np.arange(1,721,1).reshape(2,3,4,5,6)

In [181]:
d

array([[[[[  1,   2,   3,   4,   5,   6],
          [  7,   8,   9,  10,  11,  12],
          [ 13,  14,  15,  16,  17,  18],
          [ 19,  20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29,  30]],

         [[ 31,  32,  33,  34,  35,  36],
          [ 37,  38,  39,  40,  41,  42],
          [ 43,  44,  45,  46,  47,  48],
          [ 49,  50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59,  60]],

         [[ 61,  62,  63,  64,  65,  66],
          [ 67,  68,  69,  70,  71,  72],
          [ 73,  74,  75,  76,  77,  78],
          [ 79,  80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89,  90]],

         [[ 91,  92,  93,  94,  95,  96],
          [ 97,  98,  99, 100, 101, 102],
          [103, 104, 105, 106, 107, 108],
          [109, 110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119, 120]]],


        [[[121, 122, 123, 124, 125, 126],
          [127, 128, 129, 130, 131, 132],
          [133, 134, 135, 136, 137, 138],
          [139, 140, 141

## Splitting and combining of Arrays

In [2]:
import numpy as np
a=np.arange(1,5,1)

In [4]:
b=np.arange(4,10,1)

In [5]:
np.concatenate((a,b))

array([1, 2, 3, 4, 4, 5, 6, 7, 8, 9])

In [6]:
c=np.zeros(10)

In [7]:
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.concatenate((a,b),out=c)

array([1., 2., 3., 4., 4., 5., 6., 7., 8., 9.])

In [9]:
c

array([1., 2., 3., 4., 4., 5., 6., 7., 8., 9.])

### while Concatenating we must check that they must have same dimension

In [12]:
a=np.arange(1,10,1).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
b=np.arange(1,4).reshape(1,3)
b

array([[1, 2, 3]])

In [17]:
np.concatenate((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

### if we want to concatenate row-wise columns must be eqaul(vice -verse)

## * we can also concatenate by using vstack and hstack,
## * if we apply vstack on 2 1D Arrays it will be converted into 2D Array ,more over it must be of same dimension, for hstack also react different on 1D Array, it will work at axis=0
## in higher dimensions vstack and hstack are same as concatenate
## vstack ---->axis=0
## hstack......> axis=1

In [21]:
a=np.arange(1,5,1)

In [22]:
b=np.arange(2,6,1)

In [23]:
c=np.arange(3,7,1)

In [24]:
np.vstack((a,b,c))

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

# splitting

In [25]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.split(a,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [28]:
b=np.arange(1,13).reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
np.split(b,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [31]:
np.vsplit(b,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [36]:
d=np.arange(1,17).reshape(4,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [37]:
np.hsplit(d,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

# INSERT and DELETE

In [39]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## insert converts floating value to integer and insert

In [46]:
b=np.insert(a,(1,5,6,7),50.55)
b

array([ 1, 50,  2,  3,  4,  5, 50,  6, 50,  7, 50,  8,  9])

## if axis=None the input array might be of any dimension it will be flattened

In [52]:
a=np.arange(720).reshape(2,3,4,5,6)
a

array([[[[[  0,   1,   2,   3,   4,   5],
          [  6,   7,   8,   9,  10,  11],
          [ 12,  13,  14,  15,  16,  17],
          [ 18,  19,  20,  21,  22,  23],
          [ 24,  25,  26,  27,  28,  29]],

         [[ 30,  31,  32,  33,  34,  35],
          [ 36,  37,  38,  39,  40,  41],
          [ 42,  43,  44,  45,  46,  47],
          [ 48,  49,  50,  51,  52,  53],
          [ 54,  55,  56,  57,  58,  59]],

         [[ 60,  61,  62,  63,  64,  65],
          [ 66,  67,  68,  69,  70,  71],
          [ 72,  73,  74,  75,  76,  77],
          [ 78,  79,  80,  81,  82,  83],
          [ 84,  85,  86,  87,  88,  89]],

         [[ 90,  91,  92,  93,  94,  95],
          [ 96,  97,  98,  99, 100, 101],
          [102, 103, 104, 105, 106, 107],
          [108, 109, 110, 111, 112, 113],
          [114, 115, 116, 117, 118, 119]]],


        [[[120, 121, 122, 123, 124, 125],
          [126, 127, 128, 129, 130, 131],
          [132, 133, 134, 135, 136, 137],
          [138, 139, 140

In [56]:
np.insert(a,2,10000000)

array([       0,        1, 10000000,        2,        3,        4,
              5,        6,        7,        8,        9,       10,
             11,       12,       13,       14,       15,       16,
             17,       18,       19,       20,       21,       22,
             23,       24,       25,       26,       27,       28,
             29,       30,       31,       32,       33,       34,
             35,       36,       37,       38,       39,       40,
             41,       42,       43,       44,       45,       46,
             47,       48,       49,       50,       51,       52,
             53,       54,       55,       56,       57,       58,
             59,       60,       61,       62,       63,       64,
             65,       66,       67,       68,       69,       70,
             71,       72,       73,       74,       75,       76,
             77,       78,       79,       80,       81,       82,
             83,       84,       85,       86,       87,      

## for higher dimensions we can give axis=0 or axis=1
## for less columns it will regenerate , for list it must give exact size other-wise it will give error

In [59]:
a=np.arange(1,10,1).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.insert(a,2,25,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [25, 25, 25],
       [ 7,  8,  9]])

In [61]:
np.insert(a,2,25,axis=1)

array([[ 1,  2, 25,  3],
       [ 4,  5, 25,  6],
       [ 7,  8, 25,  9]])

In [64]:
np.insert(a,2,[1,2,3,4],axis=0)

ValueError: could not broadcast input array from shape (1,4) into shape (1,3)

# * we cam also use append but it will add  only at the end of the array.

## * if we append a list it must be a list[list]

In [65]:
a=np.arange(1,10,1)

In [66]:
np.append(a,5000)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9, 5000])

In [67]:
b=np.arange(1,10,1).reshape(3,3)

In [68]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
np.append(b,[[4,5,6]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 6]])

In [77]:
np.append(b,[[4],[5],[6]],axis=1)

array([[1, 2, 3, 4],
       [4, 5, 6, 5],
       [7, 8, 9, 6]])

# delete

In [79]:
a=np.arange(1,10,1)

## we must mention only index here

In [80]:
np.delete(a,2)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [84]:
b=np.random.randint(1,10,size=(3,3))
b

array([[3, 3, 3],
       [6, 5, 8],
       [5, 8, 7]])

In [87]:
np.delete(b,2)

array([3, 3, 6, 5, 8, 5, 8, 7])

In [85]:
np.delete(b,1,axis=0)

array([[3, 3, 3],
       [5, 8, 7]])

In [86]:
np.delete(b,1,axis=1)

array([[3, 3],
       [6, 8],
       [5, 7]])

# MATRIX

## Matrix is rectangular arrangement of numbers

### both array addition and matrix addition are same but difference in multiplication

In [94]:
a=np.arange(1,10,1).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
b=np.arange(11,20,1).reshape(3,3)

In [90]:
a.dot(b)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [91]:
a*b

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [95]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

 ### Creating a matrix by using Matrix Class

In [98]:
a=np.matrix("1 2;3 4")

In [99]:
a

matrix([[1, 2],
        [3, 4]])

In [101]:
b=np.matrix([[10,20],[30,40]])
b

matrix([[10, 20],
        [30, 40]])

In [102]:
a+b

matrix([[11, 22],
        [33, 44]])

In [103]:
a.dot(b)

matrix([[ 70, 100],
        [150, 220]])

In [104]:
np.transpose(b)

matrix([[10, 30],
        [20, 40]])

In [105]:
a*b

matrix([[ 70, 100],
        [150, 220]])

In [106]:
a.T

matrix([[1, 3],
        [2, 4]])

# LINEAR ALGEBRA

### invert a matrix by using linear algebra module

In [108]:
a

matrix([[1, 2],
        [3, 4]])

In [109]:
b=np.linalg.inv(a)

# A *inv(A) = I

In [110]:
a.dot(b)

matrix([[1.0000000e+00, 0.0000000e+00],
        [8.8817842e-16, 1.0000000e+00]])

## Matrix Power

## power =0(identitymatrix)
## power =-ve value (finding inverseand apply power on that matrix)
## this only works for sqaure matrix only

In [112]:
a

matrix([[1, 2],
        [3, 4]])

In [111]:
np.linalg.matrix_power(a,2)

matrix([[ 7, 10],
        [15, 22]])

In [113]:
np.linalg.matrix_power(a,0)

matrix([[1, 0],
        [0, 1]])

In [114]:
np.linalg.matrix_power(a,-1)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

## solving Linear Equation using Linear Algebra Model

### * converting linear Equations to matrix form and solving the equations
### * it must be a square matrix only

In [115]:
a=np.array([[1,2],[3,4]])

In [116]:
b=np.array([3,4])

In [117]:
np.linalg.solve(a,b)

array([-2. ,  2.5])

# DERMINANT OF Matrix

## * determent =ad-bc

In [118]:
a

array([[1, 2],
       [3, 4]])

In [121]:
np.linalg.det(a)

-2.0000000000000004

In [122]:
round(np.linalg.det(a))

-2.0

# we can find determination of any shape of matrix 